config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :cards
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
    # has_many_attached :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

    def index
        search_date = params[:search_date]
        start_datetime = search_date.to_datetime.beginning_of_day
        end_datetime = search_date.to_datetime.end_of_day
        @result = Card.where(created_at: start_datetime..end_datetime).first
        # @card = Card.where(created_at: params[:search_date]).first
    end

    def new
        @cards = Card.new
    end

    def create
        # @card = Card.new(card_params)
        @card = Card.new(arrival_time: params[:arrival_time], departure_time: params[:departure_time], arrival_image: params[:arrival_image], departure_image: params[:departure_image])
        if @card.save
            render json: @card, status: :created
          else
            render json: @card.errors, status: :unprocessable_entity
        end
    end

    def edit
        @card = Card.find_by(id: params[:id])
    end

    def update
        if @card.update(card_params)
            redirect_to "/"
        else
            render :edit
        end
    end

    def destroy
        @card = Card.find_by(id: params[:id])
        @card.destroy
        redirect_to "/"
    end

    # private
    # def card_params
    #     params.require(:card).permit(:arrival_time, :departure_time, :arrival_image, :departure_time)
    # end
    # ストロングパラメータでなぜかエラー
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cards = Card.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cards/index.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <header class="header-logo">出退勤管理システム</header>
        <main>
            <!-- 画像2枚 -->
            <div class="date-form">
                <%= form_with url: cards_path, method: :get do |f| %>
                    <%= f.label :search_date, "日付", class: 'control-label' %>
                    <%= f.date_field :search_date, class: 'form-control' %>
                    <%= f.submit "検索" %>
                <% end %>
            </div>
            <div class="images">
                <% if @result.present? %>
                    <div class="left-image">
                        <%= image_tag "data:image/png;base64, #{@result.arrival_image}" %>
                        <p>出勤  <%= @result.arrival_time %></p>
                    </div>
                    <div class="right-image">
                        <%= image_tag "data:image/png;base64, #{@result.departure_image}" %>
                        <p>退勤  <%= @result.departure_time %></p>
                    </div>
                <% else %>
                    <!-- @cardがnilの場合の処理 -->
                    <p>データなし</p>
                <% end %>
            </div>
        </main>
        <footer></footer>
    </body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <header class="header-logo">出退勤管理システム</header>
        <main>
            <!-- 画像2枚 -->
            <div class="date-form">
                <%= form_with url: cards_path, method: :get do |f| %>
                    <%= f.label :search_date, "日付", class: 'control-label' %>
                    <%= f.date_field :search_date, class: 'form-control' %>
                    <%= f.submit "検索" %>
                <% end %>
            </div>
        </main>
        <footer></footer>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeCardSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>